App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [create, edit]
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [create, edit]


App\Entity\Measurement:
  properties:
    date:
      - NotBlank:
          groups: [create, edit]
    celsius:
      - NotBlank:
          groups: [create, edit]
      - Range:
          min: -20
          max: 40
          groups: [create, edit]